services:
  - type: web
    name: jobportal-backend
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: GOOGLE_CLIENT_ID
        value: ${GOOGLE_CLIENT_ID}
      - key: GOOGLE_CLIENT_SECRET
        value: ${GOOGLE_CLIENT_SECRET}
      - key: REDIS_URL
        value: ${REDIS_URL}
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: AWS_ACCESS_KEY
        value: ${AWS_ACCESS_KEY}
      - key: AWS_SECRET_KEY
        value: ${AWS_SECRET_KEY}
      - key: S3_BUCKET
        value: ${S3_BUCKET}
      - key: APP_SECRET_KEY
        value: ${APP_SECRET_KEY}
      - key: FRONTEND_URL
        value: ${FRONTEND_URL}
    autoDeploy: true
    region: us-west-1
    instanceType: free
