services:
  - type: web
    name: jobportal-backend
    env: docker
    buildCommand: docker build -t jobportal-backend .
    startCommand: docker run -p 8080:8080 jobportal-backend
    envVars:
      - key: GOOGLE_CLIENT_ID
        fromDatabase: ${GOOGLE_CLIENT_ID}
      - key: GOOGLE_CLIENT_SECRET
        fromDatabase: ${GOOGLE_CLIENT_SECRET}
      - key: REDIS_URL
        fromDatabase: ${REDIS_URL}
      - key: MONGODB_URI
        fromDatabase: ${MONGODB_URI}
      - key: AWS_ACCESS_KEY
        fromDatabase: ${AWS_ACCESS_KEY}
      - key: AWS_SECRET_KEY
        fromDatabase: ${AWS_SECRET_KEY}
      - key: S3_BUCKET
        fromDatabase: ${S3_BUCKET}
      - key: APP_SECRET_KEY
        fromDatabase: ${APP_SECRET_KEY}
      - key: FRONTEND_URL
        fromDatabase: ${FRONTEND_URL}
    autoDeploy: true
    region: us-west-1
    instanceType: free
    plan: free
