server:
  port: 8080

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL}
    mongodb:
      write-concern: "majority"
      database: ${SPRING_DATA_MONGODB_DATABASE:Prabhat}
      uri: ${SPRING_DATA_MONGODB_URI}
      auto-index-creation: ${SPRING_DATA_MONGODB_AUTO_INDEX_CREATION:true}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${S3_BUCKET_NAME}

app:
  secret-key: ${APP_SECRET_KEY} 
