spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, email, profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  application:
    name: jobportal
  data:
    redis:
      url: ${REDIS_URL}
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DB}
      auto-index-creation: true

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: eu-north-1
    s3:
      bucket: ${S3_BUCKET}

app:
  secret-key: ${APP_SECRET_KEY}
  frontend:
    url: ${FRONTEND_URL}
